#!/usr/bin/env bash

set -euo pipefail

curl -fsSL https://mise.run/bash | sh

"$HOME/.local/bin/mise" trust
"$HOME/.local/bin/mise" install --locked \
	actionlint \
	"aqua:EmbarkStudios/cargo-deny" \
	cargo-dist \
	cargo-insta \
	rust \
	yamlfmt
